model_dir: run/indo-pacific_multitasknmt_id-en/

params:
  optimizer: LazyAdam
  optimizer_params:
    beta_1: 0.9
    beta_2: 0.998
  learning_rate: 2.0
  regularization:
    type: l2
    scale: 1e-4
  average_loss_in_time: true
  mask_loss_outliers: false
  decay_type: NoamDecay
  decay_params:
    model_dim: 768
    warmup_steps: 8000
  label_smoothing: 0.1
  beam_width: 1
  num_hypotheses: 1
  coverage_penalty: 0.0

train:
  batch_size: 768
  batch_type: tokens
  effective_batch_size: 65536
  maximum_features_length: 512
  maximum_labels_length: 512
  length_bucket_width: 1
  sample_buffer_size: 500000
  average_last_checkpoints: 0
  max_step: null
  single_pass: false
  save_summary_steps: 100
  save_checkpoints_steps: 500
  keep_checkpoint_max: 9999

eval:
  batch_size: 32
  batch_type: examples
  length_bucket_width: 5
  steps: 500
  scorers: bleu
  save_eval_predictions: true
infer:
  batch_size: 32
  batch_type: examples
  length_bucket_width: 5
score:
  batch_size: 64
  batch_type: examples
  length_bucket_width: 5

data:
  source_vocabulary: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2.vocab.sentineltoks
  target_vocabulary: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2.vocab.sentineltoks

  source_tokenization:
    type: OpenNMTTokenizer
    params:
      bpe_model_path: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2
      vocabulary_path: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2.vocab.sentineltoks
      joiner_annotate: true
      mode: aggressive
      preserve_placeholders: true
      preserve_segmented_tokens: true
      segment_case: false
      segment_numbers: true
      segment_alphabet_change: true
      segment_alphabet: ["Han", "Kanbun", "Katakana", "Hiragana"]
      no_substitution: true
      support_prior_joiners: true
  target_tokenization:
    type: OpenNMTTokenizer
    params:
      bpe_model_path: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2
      vocabulary_path: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2.vocab.sentineltoks
      joiner_annotate: true
      mode: aggressive
      preserve_placeholders: true
      preserve_segmented_tokens: true
      segment_case: false
      segment_numbers: true
      segment_alphabet_change: true
      segment_alphabet: ["Han", "Kanbun", "Katakana", "Hiragana"]
      no_substitution: true
      support_prior_joiners: true

  source_sequence_controls:
    start: true
    end: true

  target_sequence_controls:
    start: true
    end: true

  eval_features_file: data/Indo-Pacific/flores-200/dev/dev.id
  eval_labels_file:   data/Indo-Pacific/flores-200/dev/dev.en

  train_features_file:
    - data/Indo-Pacific/bilingual/en-id/CCAligned.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/ELRC-wikipedia_health.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/GNOME.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/GlobalVoices.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/KDE4.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/NLLB.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/NeuLab-TedTalks.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/News-Commentary.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/OpenSubtitles.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/QED.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/TED2020.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/Tanzil.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/Tatoeba.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/Ubuntu.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/WikiMatrix.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/XLEnt.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/bible-uedin.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/tico-19.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/tldr-pages.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/wikimedia.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/CCAligned.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/ELRC-wikipedia_health.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/GNOME.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/GlobalVoices.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/KDE4.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/NLLB.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/NeuLab-TedTalks.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/News-Commentary.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/OpenSubtitles.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/QED.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/TED2020.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/Tanzil.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/Tatoeba.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/Ubuntu.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/WikiMatrix.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/XLEnt.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/bible-uedin.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/tico-19.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/tldr-pages.en-id.id.gz
    - data/Indo-Pacific/bilingual/en-id/wikimedia.en-id.id.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - data/Indo-Pacific/monolingual/id/CCAligned_v1_id.txt.gz
    - data/Indo-Pacific/monolingual/id/ELRC-3049-wikipedia_health_v1_id.txt.gz
    - data/Indo-Pacific/monolingual/id/GNOME_v1_id.txt.gz
    - data/Indo-Pacific/monolingual/id/GlobalVoices_v2018q4_id.txt.gz
    - data/Indo-Pacific/monolingual/id/KDE4_v2_id.txt.gz
    - data/Indo-Pacific/monolingual/id/NLLB_v1_id.txt.gz
    - data/Indo-Pacific/monolingual/id/NeuLab-TedTalks_v1_id.txt.gz
    - data/Indo-Pacific/monolingual/id/News-Commentary_v16_id.txt.gz
    - data/Indo-Pacific/monolingual/id/OpenSubtitles_v2018_id.txt.gz
    - data/Indo-Pacific/monolingual/id/QED_v2.0a_id.txt.gz
    - data/Indo-Pacific/monolingual/id/TED2020_v1_id.txt.gz
    - data/Indo-Pacific/monolingual/id/Tanzil_v1_id.txt.gz
    - data/Indo-Pacific/monolingual/id/Tatoeba_v2023-04-12_id.txt.gz
    - data/Indo-Pacific/monolingual/id/Ubuntu_v14.10_id.txt.gz
    - data/Indo-Pacific/monolingual/id/WikiMatrix_v1_id.txt.gz
    - data/Indo-Pacific/monolingual/id/XLEnt_v1.2_id.txt.gz
    - data/Indo-Pacific/monolingual/id/bible-uedin_v1_id.txt.gz
    - data/Indo-Pacific/monolingual/id/tico-19_v2020-10-28_id.txt.gz
    - data/Indo-Pacific/monolingual/id/tldr-pages_v2023-08-29_id.txt.gz
    - data/Indo-Pacific/monolingual/id/wikimedia_v20230407_id.txt.gz
    - data/Indo-Pacific/monolingual/id/news.2020.id.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/id/news.2021.id.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/id/news.2022.id.shuffled.deduped.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - data/Indo-Pacific/bilingual/ceb-id/NLLB.ceb-id.id.gz
    - data/Indo-Pacific/bilingual/ceb-id/QED.ceb-id.id.gz
    - data/Indo-Pacific/bilingual/ceb-id/TED2020.ceb-id.id.gz
    - data/Indo-Pacific/bilingual/ceb-id/wikimedia.ceb-id.id.gz
    - data/Indo-Pacific/bilingual/id-bug/wikimedia.bug-id.id.gz
    - data/Indo-Pacific/bilingual/id-jv/CCMatrix.id-jv.id.gz
    - data/Indo-Pacific/bilingual/id-jv/NLLB.id-jv.id.gz
    - data/Indo-Pacific/bilingual/id-jv/QED.id-jv.id.gz
    - data/Indo-Pacific/bilingual/id-jv/Tatoeba.id-jv.id.gz
    - data/Indo-Pacific/bilingual/id-jv/WikiMatrix.id-jv.id.gz
    - data/Indo-Pacific/bilingual/id-jv/wikimedia.id-jv.id.gz
    - data/Indo-Pacific/bilingual/id-ms/ELRC-wikipedia_health.id-ms.id.gz
    - data/Indo-Pacific/bilingual/id-ms/GNOME.id-ms.id.gz
    - data/Indo-Pacific/bilingual/id-ms/KDE4.id-ms.id.gz
    - data/Indo-Pacific/bilingual/id-ms/NLLB.id-ms.id.gz
    - data/Indo-Pacific/bilingual/id-ms/NeuLab-TedTalks.id-ms.id.gz
    - data/Indo-Pacific/bilingual/id-ms/QED.id-ms.id.gz
    - data/Indo-Pacific/bilingual/id-ms/TED2020.id-ms.id.gz
    - data/Indo-Pacific/bilingual/id-ms/wikimedia.id-ms.id.gz
    - data/Indo-Pacific/bilingual/id-su/CCMatrix.id-su.id.gz
    - data/Indo-Pacific/bilingual/id-su/NLLB.id-su.id.gz
    - data/Indo-Pacific/bilingual/id-su/wikimedia.id-su.id.gz
    - data/Indo-Pacific/bilingual/ilo-id/NLLB.id-ilo.id.gz
    - data/Indo-Pacific/bilingual/tl-id/ELRC-wikipedia_health.id-tl.id.gz
    - data/Indo-Pacific/bilingual/tl-id/GNOME.id-tl.id.gz
    - data/Indo-Pacific/bilingual/tl-id/NLLB.id-tl.id.gz
    - data/Indo-Pacific/bilingual/tl-id/QED.id-tl.id.gz
    - data/Indo-Pacific/bilingual/tl-id/TED2020.id-tl.id.gz
    - data/Indo-Pacific/bilingual/tl-id/Tatoeba.id-tl.id.gz
    - data/Indo-Pacific/bilingual/tl-id/WikiMatrix.id-tl.id.gz
    - data/Indo-Pacific/bilingual/tl-id/wikimedia.id-tl.id.gz

  train_labels_file:
    - data/Indo-Pacific/bilingual/en-id/CCAligned.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/ELRC-wikipedia_health.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/GNOME.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/GlobalVoices.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/KDE4.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/NLLB.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/NeuLab-TedTalks.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/News-Commentary.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/OpenSubtitles.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/QED.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/TED2020.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/Tanzil.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/Tatoeba.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/Ubuntu.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/WikiMatrix.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/XLEnt.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/bible-uedin.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/tico-19.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/tldr-pages.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/wikimedia.en-id.en.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - data/Indo-Pacific/bilingual/en-id/CCAligned.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/ELRC-wikipedia_health.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/GNOME.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/GlobalVoices.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/KDE4.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/NLLB.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/NeuLab-TedTalks.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/News-Commentary.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/OpenSubtitles.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/QED.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/TED2020.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/Tanzil.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/Tatoeba.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/Ubuntu.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/WikiMatrix.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/XLEnt.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/bible-uedin.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/tico-19.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/tldr-pages.en-id.en.gz
    - data/Indo-Pacific/bilingual/en-id/wikimedia.en-id.en.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - data/Indo-Pacific/monolingual/en/news.2007.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2008.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2009.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2010.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2011.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2012.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2013.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2014.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2015.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2016.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2017.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2018.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2019.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2020.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2021.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2022.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/NLLB_v1_en.txt.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 