model_dir: run/indo-pacific_multitasknmt_tl-en/

params:
  optimizer: LazyAdam
  optimizer_params:
    beta_1: 0.9
    beta_2: 0.998
  learning_rate: 2.0
  regularization:
    type: l2
    scale: 1e-4
  average_loss_in_time: true
  mask_loss_outliers: false
  decay_type: NoamDecay
  decay_params:
    model_dim: 768
    warmup_steps: 8000
  label_smoothing: 0.1
  beam_width: 1
  num_hypotheses: 1
  coverage_penalty: 0.0

train:
  batch_size: 768
  batch_type: tokens
  effective_batch_size: 65536
  maximum_features_length: 512
  maximum_labels_length: 512
  length_bucket_width: 1
  sample_buffer_size: 500000
  average_last_checkpoints: 0
  max_step: null
  single_pass: false
  save_summary_steps: 100
  save_checkpoints_steps: 500
  keep_checkpoint_max: 9999

eval:
  batch_size: 32
  batch_type: examples
  length_bucket_width: 5
  steps: 500
  scorers: bleu
  save_eval_predictions: true
infer:
  batch_size: 32
  batch_type: examples
  length_bucket_width: 5
score:
  batch_size: 64
  batch_type: examples
  length_bucket_width: 5

data:
  source_vocabulary: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2.vocab.sentineltoks
  target_vocabulary: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2.vocab.sentineltoks

  source_tokenization:
    type: OpenNMTTokenizer
    params:
      bpe_model_path: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2
      vocabulary_path: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2.vocab.sentineltoks
      joiner_annotate: true
      mode: aggressive
      preserve_placeholders: true
      preserve_segmented_tokens: true
      segment_case: false
      segment_numbers: true
      segment_alphabet_change: true
      segment_alphabet: ["Han", "Kanbun", "Katakana", "Hiragana"]
      no_substitution: true
      support_prior_joiners: true
  target_tokenization:
    type: OpenNMTTokenizer
    params:
      bpe_model_path: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2
      vocabulary_path: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2.vocab.sentineltoks
      joiner_annotate: true
      mode: aggressive
      preserve_placeholders: true
      preserve_segmented_tokens: true
      segment_case: false
      segment_numbers: true
      segment_alphabet_change: true
      segment_alphabet: ["Han", "Kanbun", "Katakana", "Hiragana"]
      no_substitution: true
      support_prior_joiners: true

  source_sequence_controls:
    start: true
    end: true

  target_sequence_controls:
    start: true
    end: true

  eval_features_file: data/Indo-Pacific/flores-200/dev/dev.tl
  eval_labels_file:   data/Indo-Pacific/flores-200/dev/dev.en

  train_features_file:
    - data/Indo-Pacific/bilingual/en-tl/CCAligned.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/CCMatrix.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/ELRC-wikipedia_health.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/GNOME.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/NLLB.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/OpenSubtitles.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/ParaCrawl.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/QED.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/TED2020.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/Tatoeba.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/Ubuntu.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/WikiMatrix.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/XLEnt.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/bible-uedin.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/tico-19.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/wikimedia.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/CCAligned.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/CCMatrix.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/ELRC-wikipedia_health.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/GNOME.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/NLLB.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/OpenSubtitles.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/ParaCrawl.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/QED.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/TED2020.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/Tatoeba.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/Ubuntu.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/WikiMatrix.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/XLEnt.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/bible-uedin.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/tico-19.en-tl.tl.gz
    - data/Indo-Pacific/bilingual/en-tl/wikimedia.en-tl.tl.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - data/Indo-Pacific/monolingual/tl/CCAligned_v1_tl.txt.gz
    - data/Indo-Pacific/monolingual/tl/CCMatrix_v1_tl.txt.gz
    - data/Indo-Pacific/monolingual/tl/ELRC-3067-wikipedia_health_v1_tl.txt.gz
    - data/Indo-Pacific/monolingual/tl/GNOME_v1_tl.txt.gz
    - data/Indo-Pacific/monolingual/tl/GlobalVoices_v2018q4_fil.txt.gz
    - data/Indo-Pacific/monolingual/tl/NLLB_v1_tl.txt.gz
    - data/Indo-Pacific/monolingual/tl/OpenSubtitles_v2018_tl.txt.gz
    - data/Indo-Pacific/monolingual/tl/ParaCrawl_v9_tl.txt.gz
    - data/Indo-Pacific/monolingual/tl/QED_v2.0a_fil.txt.gz
    - data/Indo-Pacific/monolingual/tl/QED_v2.0a_tl.txt.gz
    - data/Indo-Pacific/monolingual/tl/TED2020_v1_fil.txt.gz
    - data/Indo-Pacific/monolingual/tl/TED2020_v1_tl.txt.gz
    - data/Indo-Pacific/monolingual/tl/Tatoeba_v2023-04-12_tl.txt.gz
    - data/Indo-Pacific/monolingual/tl/Ubuntu_v14.10_fil.txt.gz
    - data/Indo-Pacific/monolingual/tl/Ubuntu_v14.10_tl.txt.gz
    - data/Indo-Pacific/monolingual/tl/WikiMatrix_v1_tl.txt.gz
    - data/Indo-Pacific/monolingual/tl/XLEnt_v1.2_tl.txt.gz
    - data/Indo-Pacific/monolingual/tl/bible-uedin_v1_tl.txt.gz
    - data/Indo-Pacific/monolingual/tl/tico-19_v2020-10-28_tl.txt.gz
    - data/Indo-Pacific/monolingual/tl/wikimedia_v20230407_tl.txt.gz
    - data/Indo-Pacific/monolingual/tl/news.2020.tl.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/tl/news.2021.tl.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/tl/news.2022.tl.shuffled.deduped.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - data/Indo-Pacific/bilingual/tl-ceb/NLLB.ceb-tl.tl.gz
    - data/Indo-Pacific/bilingual/tl-ceb/QED.ceb-tl.tl.gz
    - data/Indo-Pacific/bilingual/tl-ceb/TED2020.ceb-tl.tl.gz
    - data/Indo-Pacific/bilingual/tl-ceb/Tatoeba.ceb-tl.tl.gz
    - data/Indo-Pacific/bilingual/tl-ceb/wikimedia.ceb-tl.tl.gz
    - data/Indo-Pacific/bilingual/tl-id/ELRC-wikipedia_health.id-tl.tl.gz
    - data/Indo-Pacific/bilingual/tl-id/GNOME.id-tl.tl.gz
    - data/Indo-Pacific/bilingual/tl-id/NLLB.id-tl.tl.gz
    - data/Indo-Pacific/bilingual/tl-id/QED.id-tl.tl.gz
    - data/Indo-Pacific/bilingual/tl-id/TED2020.id-tl.tl.gz
    - data/Indo-Pacific/bilingual/tl-id/Tatoeba.id-tl.tl.gz
    - data/Indo-Pacific/bilingual/tl-id/WikiMatrix.id-tl.tl.gz
    - data/Indo-Pacific/bilingual/tl-id/wikimedia.id-tl.tl.gz
    - data/Indo-Pacific/bilingual/tl-ilo/NLLB.ilo-tl.tl.gz
    - data/Indo-Pacific/bilingual/tl-jv/NLLB.jv-tl.tl.gz
    - data/Indo-Pacific/bilingual/tl-jv/QED.jv-tl.tl.gz
    - data/Indo-Pacific/bilingual/tl-ms/ELRC-wikipedia_health.ms-tl.tl.gz
    - data/Indo-Pacific/bilingual/tl-ms/GNOME.ms-tl.tl.gz
    - data/Indo-Pacific/bilingual/tl-ms/NLLB.ms-tl.tl.gz
    - data/Indo-Pacific/bilingual/tl-ms/QED.ms-tl.tl.gz
    - data/Indo-Pacific/bilingual/tl-ms/TED2020.ms-tl.tl.gz
    - data/Indo-Pacific/bilingual/tl-ms/wikimedia.ms-tl.tl.gz
    - data/Indo-Pacific/bilingual/tl-su/NLLB.su-tl.tl.gz

  train_labels_file:
    - data/Indo-Pacific/bilingual/en-tl/CCAligned.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/CCMatrix.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/ELRC-wikipedia_health.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/GNOME.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/NLLB.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/OpenSubtitles.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/ParaCrawl.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/QED.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/TED2020.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/Tatoeba.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/Ubuntu.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/WikiMatrix.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/XLEnt.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/bible-uedin.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/tico-19.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/wikimedia.en-tl.en.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - data/Indo-Pacific/bilingual/en-tl/CCAligned.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/CCMatrix.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/ELRC-wikipedia_health.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/GNOME.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/NLLB.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/OpenSubtitles.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/ParaCrawl.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/QED.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/TED2020.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/Tatoeba.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/Ubuntu.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/WikiMatrix.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/XLEnt.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/bible-uedin.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/tico-19.en-tl.en.gz
    - data/Indo-Pacific/bilingual/en-tl/wikimedia.en-tl.en.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - data/Indo-Pacific/monolingual/en/news.2007.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2008.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2009.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2010.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2011.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2012.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2013.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2014.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2015.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2016.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2017.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2018.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2019.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2020.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2021.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2022.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/NLLB_v1_en.txt.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
