model_dir: run/indo-pacific_multitasknmt_ceb-en/

params:
  optimizer: LazyAdam
  optimizer_params:
    beta_1: 0.9
    beta_2: 0.998
  learning_rate: 2.0
  regularization:
    type: l2
    scale: 1e-4
  average_loss_in_time: true
  mask_loss_outliers: false
  decay_type: NoamDecay
  decay_params:
    model_dim: 768
    warmup_steps: 8000
  label_smoothing: 0.1
  beam_width: 1
  num_hypotheses: 1
  coverage_penalty: 0.0

train:
  batch_size: 768
  batch_type: tokens
  effective_batch_size: 65536
  maximum_features_length: 512
  maximum_labels_length: 512
  length_bucket_width: 1
  sample_buffer_size: 500000
  average_last_checkpoints: 0
  max_step: null
  single_pass: false
  save_summary_steps: 100
  save_checkpoints_steps: 500
  keep_checkpoint_max: 9999

eval:
  batch_size: 32
  batch_type: examples
  length_bucket_width: 5
  steps: 500
  scorers: bleu
  save_eval_predictions: true
infer:
  batch_size: 32
  batch_type: examples
  length_bucket_width: 5
score:
  batch_size: 64
  batch_type: examples
  length_bucket_width: 5

data:
  source_vocabulary: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2.vocab.sentineltoks
  target_vocabulary: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2.vocab.sentineltoks

  source_tokenization:
    type: OpenNMTTokenizer
    params:
      bpe_model_path: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2
      vocabulary_path: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2.vocab.sentineltoks
      joiner_annotate: true
      mode: aggressive
      preserve_placeholders: true
      preserve_segmented_tokens: true
      segment_case: false
      segment_numbers: true
      segment_alphabet_change: true
      segment_alphabet: ["Han", "Kanbun", "Katakana", "Hiragana"]
      no_substitution: true
      support_prior_joiners: true
  target_tokenization:
    type: OpenNMTTokenizer
    params:
      bpe_model_path: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2
      vocabulary_path: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2.vocab.sentineltoks
      joiner_annotate: true
      mode: aggressive
      preserve_placeholders: true
      preserve_segmented_tokens: true
      segment_case: false
      segment_numbers: true
      segment_alphabet_change: true
      segment_alphabet: ["Han", "Kanbun", "Katakana", "Hiragana"]
      no_substitution: true
      support_prior_joiners: true

  source_sequence_controls:
    start: true
    end: true

  target_sequence_controls:
    start: true
    end: true

  eval_features_file: data/Indo-Pacific/flores-200/dev/dev.ceb
  eval_labels_file:   data/Indo-Pacific/flores-200/dev/dev.en

  train_features_file:
    - data/Indo-Pacific/bilingual/en-ceb/CCMatrix.ceb-en.ceb.gz
    - data/Indo-Pacific/bilingual/en-ceb/NLLB.ceb-en.ceb.gz
    - data/Indo-Pacific/bilingual/en-ceb/QED.ceb-en.ceb.gz
    - data/Indo-Pacific/bilingual/en-ceb/TED2020.ceb-en.ceb.gz
    - data/Indo-Pacific/bilingual/en-ceb/Tatoeba.ceb-en.ceb.gz
    - data/Indo-Pacific/bilingual/en-ceb/Ubuntu.ceb-en.ceb.gz
    - data/Indo-Pacific/bilingual/en-ceb/WikiMatrix.ceb-en.ceb.gz
    - data/Indo-Pacific/bilingual/en-ceb/XLEnt.ceb-en.ceb.gz
    - data/Indo-Pacific/bilingual/en-ceb/bible-uedin.ceb-en.ceb.gz
    - data/Indo-Pacific/bilingual/en-ceb/wikimedia.ceb-en.ceb.gz
    - data/Indo-Pacific/bilingual/en-ceb/CCMatrix.ceb-en.ceb.gz
    - data/Indo-Pacific/bilingual/en-ceb/NLLB.ceb-en.ceb.gz
    - data/Indo-Pacific/bilingual/en-ceb/QED.ceb-en.ceb.gz
    - data/Indo-Pacific/bilingual/en-ceb/TED2020.ceb-en.ceb.gz
    - data/Indo-Pacific/bilingual/en-ceb/Tatoeba.ceb-en.ceb.gz
    - data/Indo-Pacific/bilingual/en-ceb/Ubuntu.ceb-en.ceb.gz
    - data/Indo-Pacific/bilingual/en-ceb/WikiMatrix.ceb-en.ceb.gz
    - data/Indo-Pacific/bilingual/en-ceb/XLEnt.ceb-en.ceb.gz
    - data/Indo-Pacific/bilingual/en-ceb/bible-uedin.ceb-en.ceb.gz
    - data/Indo-Pacific/bilingual/en-ceb/wikimedia.ceb-en.ceb.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - data/Indo-Pacific/monolingual/ceb/CCMatrix_v1_ceb.txt.gz
    - data/Indo-Pacific/monolingual/ceb/NLLB_v1_ceb.txt.gz
    - data/Indo-Pacific/monolingual/ceb/QED_v2.0a_ceb.txt.gz
    - data/Indo-Pacific/monolingual/ceb/TED2020_v1_ceb.txt.gz
    - data/Indo-Pacific/monolingual/ceb/Tatoeba_v2023-04-12_ceb.txt.gz
    - data/Indo-Pacific/monolingual/ceb/Ubuntu_v14.10_ceb.txt.gz
    - data/Indo-Pacific/monolingual/ceb/WikiMatrix_v1_ceb.txt.gz
    - data/Indo-Pacific/monolingual/ceb/XLEnt_v1.2_ceb.txt.gz
    - data/Indo-Pacific/monolingual/ceb/bible-uedin_v1_ceb.txt.gz
    - data/Indo-Pacific/monolingual/ceb/wikimedia_v20230407_ceb.txt.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - data/Indo-Pacific/bilingual/ceb-bug/NLLB.bug-ceb.ceb.gz
    - data/Indo-Pacific/bilingual/ceb-id/NLLB.ceb-id.ceb.gz
    - data/Indo-Pacific/bilingual/ceb-id/QED.ceb-id.ceb.gz
    - data/Indo-Pacific/bilingual/ceb-id/TED2020.ceb-id.ceb.gz
    - data/Indo-Pacific/bilingual/ceb-id/wikimedia.ceb-id.ceb.gz
    - data/Indo-Pacific/bilingual/ceb-ilo/CCMatrix.ceb-ilo.ceb.gz
    - data/Indo-Pacific/bilingual/ceb-ilo/NLLB.ceb-ilo.ceb.gz
    - data/Indo-Pacific/bilingual/ceb-jv/CCMatrix.ceb-jv.ceb.gz
    - data/Indo-Pacific/bilingual/ceb-jv/NLLB.ceb-jv.ceb.gz
    - data/Indo-Pacific/bilingual/ceb-ms/NLLB.ceb-ms.ceb.gz
    - data/Indo-Pacific/bilingual/ceb-ms/QED.ceb-ms.ceb.gz
    - data/Indo-Pacific/bilingual/ceb-ms/TED2020.ceb-ms.ceb.gz
    - data/Indo-Pacific/bilingual/ceb-ms/wikimedia.ceb-ms.ceb.gz
    - data/Indo-Pacific/bilingual/ceb-su/CCMatrix.ceb-su.ceb.gz
    - data/Indo-Pacific/bilingual/ceb-su/NLLB.ceb-su.ceb.gz
    - data/Indo-Pacific/bilingual/tl-ceb/NLLB.ceb-tl.ceb.gz
    - data/Indo-Pacific/bilingual/tl-ceb/QED.ceb-tl.ceb.gz
    - data/Indo-Pacific/bilingual/tl-ceb/TED2020.ceb-tl.ceb.gz
    - data/Indo-Pacific/bilingual/tl-ceb/Tatoeba.ceb-tl.ceb.gz
    - data/Indo-Pacific/bilingual/tl-ceb/wikimedia.ceb-tl.ceb.gz


  train_labels_file:
    - data/Indo-Pacific/bilingual/en-ceb/CCMatrix.ceb-en.en.gz
    - data/Indo-Pacific/bilingual/en-ceb/NLLB.ceb-en.en.gz
    - data/Indo-Pacific/bilingual/en-ceb/QED.ceb-en.en.gz
    - data/Indo-Pacific/bilingual/en-ceb/TED2020.ceb-en.en.gz
    - data/Indo-Pacific/bilingual/en-ceb/Tatoeba.ceb-en.en.gz
    - data/Indo-Pacific/bilingual/en-ceb/Ubuntu.ceb-en.en.gz
    - data/Indo-Pacific/bilingual/en-ceb/WikiMatrix.ceb-en.en.gz
    - data/Indo-Pacific/bilingual/en-ceb/XLEnt.ceb-en.en.gz
    - data/Indo-Pacific/bilingual/en-ceb/bible-uedin.ceb-en.en.gz
    - data/Indo-Pacific/bilingual/en-ceb/wikimedia.ceb-en.en.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - data/Indo-Pacific/bilingual/en-ceb/CCMatrix.ceb-en.en.gz
    - data/Indo-Pacific/bilingual/en-ceb/NLLB.ceb-en.en.gz
    - data/Indo-Pacific/bilingual/en-ceb/QED.ceb-en.en.gz
    - data/Indo-Pacific/bilingual/en-ceb/TED2020.ceb-en.en.gz
    - data/Indo-Pacific/bilingual/en-ceb/Tatoeba.ceb-en.en.gz
    - data/Indo-Pacific/bilingual/en-ceb/Ubuntu.ceb-en.en.gz
    - data/Indo-Pacific/bilingual/en-ceb/WikiMatrix.ceb-en.en.gz
    - data/Indo-Pacific/bilingual/en-ceb/XLEnt.ceb-en.en.gz
    - data/Indo-Pacific/bilingual/en-ceb/bible-uedin.ceb-en.en.gz
    - data/Indo-Pacific/bilingual/en-ceb/wikimedia.ceb-en.en.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - data/Indo-Pacific/monolingual/en/news.2007.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2008.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2009.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2010.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2011.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2012.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2013.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2014.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2015.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2016.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2017.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2018.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2019.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2020.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2021.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2022.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/NLLB_v1_en.txt.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 