model_dir: run/indo-pacific_multitasknmt_ms-en/

params:
  optimizer: LazyAdam
  optimizer_params:
    beta_1: 0.9
    beta_2: 0.998
  learning_rate: 2.0
  regularization:
    type: l2
    scale: 1e-4
  average_loss_in_time: true
  mask_loss_outliers: false
  decay_type: NoamDecay
  decay_params:
    model_dim: 768
    warmup_steps: 8000
  label_smoothing: 0.1
  beam_width: 1
  num_hypotheses: 1
  coverage_penalty: 0.0

train:
  batch_size: 768
  batch_type: tokens
  effective_batch_size: 65536
  maximum_features_length: 512
  maximum_labels_length: 512
  length_bucket_width: 1
  sample_buffer_size: 500000
  average_last_checkpoints: 0
  max_step: null
  single_pass: false
  save_summary_steps: 100
  save_checkpoints_steps: 500
  keep_checkpoint_max: 9999

eval:
  batch_size: 32
  batch_type: examples
  length_bucket_width: 5
  steps: 500
  scorers: bleu
  save_eval_predictions: true
infer:
  batch_size: 32
  batch_type: examples
  length_bucket_width: 5
score:
  batch_size: 64
  batch_type: examples
  length_bucket_width: 5

data:
  source_vocabulary: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2.vocab.sentineltoks
  target_vocabulary: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2.vocab.sentineltoks

  source_tokenization:
    type: OpenNMTTokenizer
    params:
      bpe_model_path: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2
      vocabulary_path: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2.vocab.sentineltoks
      joiner_annotate: true
      mode: aggressive
      preserve_placeholders: true
      preserve_segmented_tokens: true
      segment_case: false
      segment_numbers: true
      segment_alphabet_change: true
      segment_alphabet: ["Han", "Kanbun", "Katakana", "Hiragana"]
      no_substitution: true
      support_prior_joiners: true
  target_tokenization:
    type: OpenNMTTokenizer
    params:
      bpe_model_path: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2
      vocabulary_path: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2.vocab.sentineltoks
      joiner_annotate: true
      mode: aggressive
      preserve_placeholders: true
      preserve_segmented_tokens: true
      segment_case: false
      segment_numbers: true
      segment_alphabet_change: true
      segment_alphabet: ["Han", "Kanbun", "Katakana", "Hiragana"]
      no_substitution: true
      support_prior_joiners: true

  source_sequence_controls:
    start: true
    end: true

  target_sequence_controls:
    start: true
    end: true

  eval_features_file: data/Indo-Pacific/flores-200/dev/dev.ms
  eval_labels_file:   data/Indo-Pacific/flores-200/dev/dev.en

  train_features_file:
    - data/Indo-Pacific/bilingual/en-ms/CCAligned.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/CCMatrix.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/ELRC-wikipedia_health.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/GNOME.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/KDE4.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/NLLB.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/NeuLab-TedTalks.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/OpenSubtitles.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/QED.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/TED2020.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/Tanzil.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/Ubuntu.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/XLEnt.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/tico-19.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/wikimedia.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/CCAligned.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/CCMatrix.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/ELRC-wikipedia_health.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/GNOME.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/KDE4.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/NLLB.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/NeuLab-TedTalks.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/OpenSubtitles.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/QED.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/TED2020.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/Tanzil.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/Ubuntu.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/XLEnt.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/tico-19.en-ms.ms.gz
    - data/Indo-Pacific/bilingual/en-ms/wikimedia.en-ms.ms.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - data/Indo-Pacific/monolingual/ms/CCAligned_v1_ms.txt.gz
    - data/Indo-Pacific/monolingual/ms/CCMatrix_v1_ms.txt.gz
    - data/Indo-Pacific/monolingual/ms/ELRC-3088-wikipedia_health_v1_ms.txt.gz
    - data/Indo-Pacific/monolingual/ms/GNOME_v1_ms.txt.gz
    - data/Indo-Pacific/monolingual/ms/KDE4_v2_ms.txt.gz
    - data/Indo-Pacific/monolingual/ms/NLLB_v1_ms.txt.gz
    - data/Indo-Pacific/monolingual/ms/NeuLab-TedTalks_v1_ms.txt.gz
    - data/Indo-Pacific/monolingual/ms/OpenSubtitles_v2018_ms.txt.gz
    - data/Indo-Pacific/monolingual/ms/QED_v2.0a_ms.txt.gz
    - data/Indo-Pacific/monolingual/ms/TED2020_v1_ms.txt.gz
    - data/Indo-Pacific/monolingual/ms/Tanzil_v1_ms.txt.gz
    - data/Indo-Pacific/monolingual/ms/Tatoeba_v2023-04-12_zlm.txt.gz
    - data/Indo-Pacific/monolingual/ms/Tatoeba_v2023-04-12_zsm.txt.gz
    - data/Indo-Pacific/monolingual/ms/Ubuntu_v14.10_ms.txt.gz
    - data/Indo-Pacific/monolingual/ms/XLEnt_v1.2_ms.txt.gz
    - data/Indo-Pacific/monolingual/ms/tico-19_v2020-10-28_ms.txt.gz
    - data/Indo-Pacific/monolingual/ms/wikimedia_v20230407_ms.txt.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - data/Indo-Pacific/bilingual/ceb-ms/NLLB.ceb-ms.ms.gz
    - data/Indo-Pacific/bilingual/ceb-ms/QED.ceb-ms.ms.gz
    - data/Indo-Pacific/bilingual/ceb-ms/TED2020.ceb-ms.ms.gz
    - data/Indo-Pacific/bilingual/ceb-ms/wikimedia.ceb-ms.ms.gz
    - data/Indo-Pacific/bilingual/id-ms/ELRC-wikipedia_health.id-ms.ms.gz
    - data/Indo-Pacific/bilingual/id-ms/GNOME.id-ms.ms.gz
    - data/Indo-Pacific/bilingual/id-ms/KDE4.id-ms.ms.gz
    - data/Indo-Pacific/bilingual/id-ms/NLLB.id-ms.ms.gz
    - data/Indo-Pacific/bilingual/id-ms/NeuLab-TedTalks.id-ms.ms.gz
    - data/Indo-Pacific/bilingual/id-ms/QED.id-ms.ms.gz
    - data/Indo-Pacific/bilingual/id-ms/TED2020.id-ms.ms.gz
    - data/Indo-Pacific/bilingual/id-ms/wikimedia.id-ms.ms.gz
    - data/Indo-Pacific/bilingual/ilo-ms/NLLB.ilo-ms.ms.gz
    - data/Indo-Pacific/bilingual/ms-jv/NLLB.jv-ms.ms.gz
    - data/Indo-Pacific/bilingual/ms-jv/QED.jv-ms.ms.gz
    - data/Indo-Pacific/bilingual/ms-jv/wikimedia.jv-ms.ms.gz
    - data/Indo-Pacific/bilingual/ms-su/NLLB.ms-su.ms.gz
    - data/Indo-Pacific/bilingual/ms-su/wikimedia.ms-su.ms.gz
    - data/Indo-Pacific/bilingual/tl-ms/ELRC-wikipedia_health.ms-tl.ms.gz
    - data/Indo-Pacific/bilingual/tl-ms/GNOME.ms-tl.ms.gz
    - data/Indo-Pacific/bilingual/tl-ms/NLLB.ms-tl.ms.gz
    - data/Indo-Pacific/bilingual/tl-ms/QED.ms-tl.ms.gz
    - data/Indo-Pacific/bilingual/tl-ms/TED2020.ms-tl.ms.gz
    - data/Indo-Pacific/bilingual/tl-ms/wikimedia.ms-tl.ms.gz

  train_labels_file:
    - data/Indo-Pacific/bilingual/en-ms/CCAligned.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/CCMatrix.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/ELRC-wikipedia_health.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/GNOME.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/KDE4.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/NLLB.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/NeuLab-TedTalks.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/OpenSubtitles.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/QED.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/TED2020.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/Tanzil.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/Ubuntu.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/XLEnt.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/tico-19.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/wikimedia.en-ms.en.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - data/Indo-Pacific/bilingual/en-ms/CCAligned.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/CCMatrix.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/ELRC-wikipedia_health.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/GNOME.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/KDE4.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/NLLB.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/NeuLab-TedTalks.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/OpenSubtitles.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/QED.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/TED2020.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/Tanzil.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/Ubuntu.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/XLEnt.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/tico-19.en-ms.en.gz
    - data/Indo-Pacific/bilingual/en-ms/wikimedia.en-ms.en.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - data/Indo-Pacific/monolingual/en/news.2007.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2008.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2009.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2010.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2011.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2012.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2013.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2014.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2015.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2016.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2017.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2018.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2019.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2020.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2021.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2022.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/NLLB_v1_en.txt.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 