model_dir: run/indo-pacific_multitasknmt_jv-en/

params:
  optimizer: LazyAdam
  optimizer_params:
    beta_1: 0.9
    beta_2: 0.998
  learning_rate: 2.0
  regularization:
    type: l2
    scale: 1e-4
  average_loss_in_time: true
  mask_loss_outliers: false
  decay_type: NoamDecay
  decay_params:
    model_dim: 768
    warmup_steps: 8000
  label_smoothing: 0.1
  beam_width: 1
  num_hypotheses: 1
  coverage_penalty: 0.0

train:
  batch_size: 768
  batch_type: tokens
  effective_batch_size: 65536
  maximum_features_length: 512
  maximum_labels_length: 512
  length_bucket_width: 1
  sample_buffer_size: 500000
  average_last_checkpoints: 0
  max_step: null
  single_pass: false
  save_summary_steps: 100
  save_checkpoints_steps: 500
  keep_checkpoint_max: 9999

eval:
  batch_size: 32
  batch_type: examples
  length_bucket_width: 5
  steps: 500
  scorers: bleu
  save_eval_predictions: true
infer:
  batch_size: 32
  batch_type: examples
  length_bucket_width: 5
score:
  batch_size: 64
  batch_type: examples
  length_bucket_width: 5

data:
  source_vocabulary: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2.vocab.sentineltoks
  target_vocabulary: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2.vocab.sentineltoks

  source_tokenization:
    type: OpenNMTTokenizer
    params:
      bpe_model_path: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2
      vocabulary_path: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2.vocab.sentineltoks
      joiner_annotate: true
      mode: aggressive
      preserve_placeholders: true
      preserve_segmented_tokens: true
      segment_case: false
      segment_numbers: true
      segment_alphabet_change: true
      segment_alphabet: ["Han", "Kanbun", "Katakana", "Hiragana"]
      no_substitution: true
      support_prior_joiners: true
  target_tokenization:
    type: OpenNMTTokenizer
    params:
      bpe_model_path: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2
      vocabulary_path: data/Indo-Pacific_vocab/pyonmt_bpe_indo-pacific_32k_min2.vocab.sentineltoks
      joiner_annotate: true
      mode: aggressive
      preserve_placeholders: true
      preserve_segmented_tokens: true
      segment_case: false
      segment_numbers: true
      segment_alphabet_change: true
      segment_alphabet: ["Han", "Kanbun", "Katakana", "Hiragana"]
      no_substitution: true
      support_prior_joiners: true

  source_sequence_controls:
    start: true
    end: true

  target_sequence_controls:
    start: true
    end: true

  eval_features_file: data/Indo-Pacific/flores-200/dev/dev.jv
  eval_labels_file:   data/Indo-Pacific/flores-200/dev/dev.en

  train_features_file:
    - data/Indo-Pacific/bilingual/en-jv/CCAligned.en-jv.jv.gz
    - data/Indo-Pacific/bilingual/en-jv/CCMatrix.en-jv.jv.gz
    - data/Indo-Pacific/bilingual/en-jv/NLLB.en-jv.jv.gz
    - data/Indo-Pacific/bilingual/en-jv/QED.en-jv.jv.gz
    - data/Indo-Pacific/bilingual/en-jv/Tatoeba.en-jv.jv.gz
    - data/Indo-Pacific/bilingual/en-jv/Ubuntu.en-jv.jv.gz
    - data/Indo-Pacific/bilingual/en-jv/WikiMatrix.en-jv.jv.gz
    - data/Indo-Pacific/bilingual/en-jv/XLEnt.en-jv.jv.gz
    - data/Indo-Pacific/bilingual/en-jv/wikimedia.en-jv.jv.gz
    - data/Indo-Pacific/bilingual/en-jv/CCAligned.en-jv.jv.gz
    - data/Indo-Pacific/bilingual/en-jv/CCMatrix.en-jv.jv.gz
    - data/Indo-Pacific/bilingual/en-jv/NLLB.en-jv.jv.gz
    - data/Indo-Pacific/bilingual/en-jv/QED.en-jv.jv.gz
    - data/Indo-Pacific/bilingual/en-jv/Tatoeba.en-jv.jv.gz
    - data/Indo-Pacific/bilingual/en-jv/Ubuntu.en-jv.jv.gz
    - data/Indo-Pacific/bilingual/en-jv/WikiMatrix.en-jv.jv.gz
    - data/Indo-Pacific/bilingual/en-jv/XLEnt.en-jv.jv.gz
    - data/Indo-Pacific/bilingual/en-jv/wikimedia.en-jv.jv.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - data/Indo-Pacific/monolingual/jv/CCAligned_v1_jv.txt.gz
    - data/Indo-Pacific/monolingual/jv/CCMatrix_v1_jv.txt.gz
    - data/Indo-Pacific/monolingual/jv/NLLB_v1_jv.txt.gz
    - data/Indo-Pacific/monolingual/jv/QED_v2.0a_jv.txt.gz
    - data/Indo-Pacific/monolingual/jv/Tatoeba_v2023-04-12_jv.txt.gz
    - data/Indo-Pacific/monolingual/jv/Ubuntu_v14.10_jv.txt.gz
    - data/Indo-Pacific/monolingual/jv/WikiMatrix_v1_jv.txt.gz
    - data/Indo-Pacific/monolingual/jv/XLEnt_v1.2_jv.txt.gz
    - data/Indo-Pacific/monolingual/jv/wikimedia_v20230407_jv.txt.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - data/Indo-Pacific/bilingual/ceb-jv/CCMatrix.ceb-jv.jv.gz
    - data/Indo-Pacific/bilingual/ceb-jv/NLLB.ceb-jv.jv.gz
    - data/Indo-Pacific/bilingual/id-jv/CCMatrix.id-jv.jv.gz
    - data/Indo-Pacific/bilingual/id-jv/NLLB.id-jv.jv.gz
    - data/Indo-Pacific/bilingual/id-jv/QED.id-jv.jv.gz
    - data/Indo-Pacific/bilingual/id-jv/Tatoeba.id-jv.jv.gz
    - data/Indo-Pacific/bilingual/id-jv/WikiMatrix.id-jv.jv.gz
    - data/Indo-Pacific/bilingual/id-jv/wikimedia.id-jv.jv.gz
    - data/Indo-Pacific/bilingual/ilo-jv/CCMatrix.ilo-jv.jv.gz
    - data/Indo-Pacific/bilingual/ilo-jv/NLLB.ilo-jv.jv.gz
    - data/Indo-Pacific/bilingual/jv-bug/NLLB.bug-jv.jv.gz
    - data/Indo-Pacific/bilingual/jv-su/CCMatrix.jv-su.jv.gz
    - data/Indo-Pacific/bilingual/jv-su/NLLB.jv-su.jv.gz
    - data/Indo-Pacific/bilingual/ms-jv/NLLB.jv-ms.jv.gz
    - data/Indo-Pacific/bilingual/ms-jv/QED.jv-ms.jv.gz
    - data/Indo-Pacific/bilingual/ms-jv/wikimedia.jv-ms.jv.gz
    - data/Indo-Pacific/bilingual/tl-jv/NLLB.jv-tl.jv.gz
    - data/Indo-Pacific/bilingual/tl-jv/QED.jv-tl.jv.gz


  train_labels_file:
    - data/Indo-Pacific/bilingual/en-jv/CCAligned.en-jv.en.gz
    - data/Indo-Pacific/bilingual/en-jv/CCMatrix.en-jv.en.gz
    - data/Indo-Pacific/bilingual/en-jv/NLLB.en-jv.en.gz
    - data/Indo-Pacific/bilingual/en-jv/QED.en-jv.en.gz
    - data/Indo-Pacific/bilingual/en-jv/Tatoeba.en-jv.en.gz
    - data/Indo-Pacific/bilingual/en-jv/Ubuntu.en-jv.en.gz
    - data/Indo-Pacific/bilingual/en-jv/WikiMatrix.en-jv.en.gz
    - data/Indo-Pacific/bilingual/en-jv/XLEnt.en-jv.en.gz
    - data/Indo-Pacific/bilingual/en-jv/wikimedia.en-jv.en.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - data/Indo-Pacific/bilingual/en-jv/CCAligned.en-jv.en.gz
    - data/Indo-Pacific/bilingual/en-jv/CCMatrix.en-jv.en.gz
    - data/Indo-Pacific/bilingual/en-jv/NLLB.en-jv.en.gz
    - data/Indo-Pacific/bilingual/en-jv/QED.en-jv.en.gz
    - data/Indo-Pacific/bilingual/en-jv/Tatoeba.en-jv.en.gz
    - data/Indo-Pacific/bilingual/en-jv/Ubuntu.en-jv.en.gz
    - data/Indo-Pacific/bilingual/en-jv/WikiMatrix.en-jv.en.gz
    - data/Indo-Pacific/bilingual/en-jv/XLEnt.en-jv.en.gz
    - data/Indo-Pacific/bilingual/en-jv/wikimedia.en-jv.en.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - data/Indo-Pacific/monolingual/en/news.2007.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2008.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2009.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2010.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2011.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2012.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2013.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2014.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2015.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2016.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2017.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2018.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2019.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2020.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2021.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/news.2022.en.shuffled.deduped.gz
    - data/Indo-Pacific/monolingual/en/NLLB_v1_en.txt.gz
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
