model_dir: run/koen_multitask/

params:
  optimizer: LazyAdam
  optimizer_params:
    beta_1: 0.9
    beta_2: 0.998
  learning_rate: 2.0
  regularization:
    type: l2
    scale: 1e-4
  average_loss_in_time: true
  mask_loss_outliers: false
  decay_type: NoamDecay
  decay_params:
    model_dim: 768
    warmup_steps: 8000
  label_smoothing: 0.1
  beam_width: 1
  num_hypotheses: 1
  coverage_penalty: 0.0

train:
  batch_size: 768
  batch_type: tokens
  effective_batch_size: 65536
  save_checkpoints_steps: 500
  keep_checkpoint_max: 1000 #it will keep all the previous models 0 and -1 gave an error message :
  save_summary_steps: 100
  max_step: null
  single_pass: false
  maximum_features_length: 512
  maximum_labels_length: 512
  length_bucket_width: 1
  sample_buffer_size: 500000
  average_last_checkpoints: 0

eval:
  batch_size: 128
  batch_type: examples
  steps: 500
  scorers: bleu
  save_eval_predictions: true

infer:
  batch_size: 128
  batch_type: examples

score:
  batch_size: 128
  batch_type: examples


data:
  source_vocabulary: data/enkovocab/pyonmt_bpe_enko_32k_min2_casemarkup.vocab
  target_vocabulary: data/enkovocab/pyonmt_bpe_enko_32k_min2_casemarkup.vocab

  source_tokenization:
    type: OpenNMTTokenizer
    params:
      joiner_annotate: true
      mode: aggressive
      no_substitution: true
      segment_alphabet_change: true
      segment_alphabet: ["Han", "Kanbun", "Katakana", "Hiragana"]
      bpe_model_path: data/enkovocab/pyonmt_bpe_enko_32k_min2.model
      segment_numbers: true
      preserve_segmented_tokens: true
      support_prior_joiners: true
      case_markup: true
      segment_case: true
      preserve_placeholders: true

  target_tokenization:
    type: OpenNMTTokenizer
    params:
      joiner_annotate: true
      mode: aggressive
      no_substitution: true
      segment_alphabet_change: true
      segment_alphabet: ["Han", "Kanbun", "Katakana", "Hiragana"]
      bpe_model_path: data/enkovocab/pyonmt_bpe_enko_32k_min2.model
      segment_numbers: true
      preserve_segmented_tokens: true
      support_prior_joiners: true
      case_markup: true
      segment_case: true
      preserve_placeholders: true

  source_sequence_controls:
    start: true
    end: true

  target_sequence_controls:
    start: true
    end: true

  eval_features_file: data/enko/testset/flores200-mttt-tatoeba20210807-dev.ko
  eval_labels_file:   data/enko/testset/flores200-mttt-tatoeba20210807-dev.en

  train_features_file:
    - data/enko/opus/CCMatrix.en-ko.ko.gz
    - data/enko/opus/CCAligned.en-ko.ko.gz
    - data/enko/opus/LinguaTools-WikiTitles.en-ko.ko.gz
    - data/enko/opus/ParaCrawl.en-ko.ko.gz
    - data/enko/opus/XLEnt.en-ko.ko.gz
    - data/enko/opus/OpenSubtitles.en-ko.ko.gz
    - data/enko/opus/QED.en-ko.ko.gz
    - data/enko/opus/TED2020.en-ko.ko.gz
    - data/enko/opus/WikiMatrix.en-ko.ko.gz
    - data/enko/opus/NeuLab-TedTalks.en-ko.ko.gz
    - data/enko/opus/wikimedia.en-ko.ko.gz
    - data/enko/opus/Tanzil.en-ko.ko.gz
    - data/enko/opus/KDE4.en-ko.ko.gz
    - data/enko/opus/bible-uedin.en-ko.ko.gz
    - data/enko/opus/PHP.en-ko.ko.gz
    - data/enko/opus/GlobalVoices.en-ko.ko.gz
    - data/enko/opus/Tatoeba.en-ko.ko.gz
    - data/enko/opus/ELRC-3070-wikipedia_health.en-ko.ko.gz
    - data/enko/opus/ELRC-wikipedia_health.en-ko.ko.gz
    - data/enko/opus/ELRC_2922.en-ko.ko.gz
    - data/enko/opus/Ubuntu.en-ko.ko.gz
    - data/enko/opus/GNOME.en-ko.ko.gz
    - data/enko/mttt/mttt_train_en-ko.raw.ko.gz
    - data/enko/opus/CCMatrix.en-ko.en.gz
    - data/enko/opus/CCAligned.en-ko.en.gz
    - data/enko/opus/LinguaTools-WikiTitles.en-ko.en.gz
    - data/enko/opus/ParaCrawl.en-ko.en.gz
    - data/enko/opus/XLEnt.en-ko.en.gz
    - data/enko/opus/OpenSubtitles.en-ko.en.gz
    - data/enko/opus/QED.en-ko.en.gz
    - data/enko/opus/TED2020.en-ko.en.gz
    - data/enko/opus/WikiMatrix.en-ko.en.gz
    - data/enko/opus/NeuLab-TedTalks.en-ko.en.gz
    - data/enko/opus/wikimedia.en-ko.en.gz
    - data/enko/opus/Tanzil.en-ko.en.gz
    - data/enko/opus/KDE4.en-ko.en.gz
    - data/enko/opus/bible-uedin.en-ko.en.gz
    - data/enko/opus/PHP.en-ko.en.gz
    - data/enko/opus/GlobalVoices.en-ko.en.gz
    - data/enko/opus/Tatoeba.en-ko.en.gz
    - data/enko/opus/ELRC-3070-wikipedia_health.en-ko.en.gz
    - data/enko/opus/ELRC-wikipedia_health.en-ko.en.gz
    - data/enko/opus/ELRC_2922.en-ko.en.gz
    - data/enko/opus/Ubuntu.en-ko.en.gz
    - data/enko/opus/GNOME.en-ko.en.gz
    - data/enko/mttt/mttt_train_en-ko.raw.en.gz
    - data/en/opus/OPUS-CCMatrix_v1_mono.en.gz 
    - data/en/opus/OPUS-CCAligned_v1_mono.en.gz 
    - data/en/opus/OPUS-OpenSubtitles_v2018_mono.en.gz 
    - data/en/opus/OPUS-LinguaTools-WikiTitles_v2014_mono.en.gz 
    - data/en/opus/OPUS-XLEnt_v1.2_mono.en.gz 
    - data/en/opus/OPUS-WikiMatrix_v1_mono.en.gz 
    - data/en/opus/OPUS-wikimedia_v20230407_mono.en.gz 
    - data/en/opus/OPUS-QED_v2.0a_mono.en.gz 
    - data/en/opus/OPUS-Tatoeba_v2023-04-12_mono.en.gz 
    - data/en/opus/OPUS-GlobalVoices_v2018q4_mono.en.gz 
    - data/en/opus/OPUS-TED2020_v1_mono.en.gz 
    - data/en/opus/OPUS-NeuLab-TedTalks_v1_mono.en.gz 
    - data/en/opus/OPUS-KDE4_v2_mono.en.gz 
    - data/en/opus/OPUS-Tanzil_v1_mono.en.gz 
    - data/en/opus/OPUS-ELRC_2922_v1_mono.en.gz 
    - data/en/opus/OPUS-bible-uedin_v1_mono.en.gz 
    - data/en/opus/OPUS-Mozilla-I10n_v1_mono.en.gz 
    - data/en/opus/OPUS-ELRC-wikipedia_health_v1_mono.en.gz 
    - data/en/opus/OPUS-GNOME_v1_mono.en.gz 
    - data/en/opus/OPUS-ELRC-3070-wikipedia_health_v1_mono.en.gz 
    - data/en/opus/OPUS-Ubuntu_v14.10_mono.en.gz 
    - data/en/wmt/news.2007.en.shuffled.deduped.gz 
    - data/en/wmt/news.2008.en.shuffled.deduped.gz 
    - data/en/wmt/news.2009.en.shuffled.deduped.gz 
    - data/en/wmt/news.2010.en.shuffled.deduped.gz 
    - data/en/wmt/news.2011.en.shuffled.deduped.gz 
    - data/en/wmt/news.2012.en.shuffled.deduped.gz 
    - data/en/wmt/news.2013.en.shuffled.deduped.gz 
    - data/en/wmt/news.2014.en.shuffled.deduped.gz 
    - data/en/wmt/news.2015.en.shuffled.deduped.gz 
    - data/en/wmt/news.2016.en.shuffled.deduped.gz 
    - data/en/wmt/news.2017.en.shuffled.deduped.gz 
    - data/en/wmt/news.2018.en.shuffled.deduped.gz 
    - data/en/wmt/news.2019.en.shuffled.deduped.gz 
    - data/en/wmt/news.2020.en.shuffled.deduped.gz 
    - data/en/wmt/news.2021.en.shuffled.deduped.gz 
    - data/en/wmt/news.2022.en.shuffled.deduped.gz 
    - data/ko/opus/OPUS-CCMatrix_v1_mono.ko.gz 
    - data/ko/opus/OPUS-LinguaTools-WikiTitles_v2014_mono.ko.gz 
    - data/ko/opus/OPUS-CCAligned_v1_mono.ko.gz 
    - data/ko/opus/OPUS-ParaCrawl_v9_mono.ko.gz 
    - data/ko/opus/OPUS-WikiMatrix_v1_mono.ko.gz 
    - data/ko/opus/OPUS-XLEnt_v1.2_mono.ko.gz 
    - data/ko/opus/OPUS-OpenSubtitles_v2018_mono.ko.gz 
    - data/ko/opus/OPUS-QED_v2.0a_mono.ko.gz 
    - data/ko/opus/OPUS-TED2020_v1_mono.ko.gz 
    - data/ko/opus/OPUS-NeuLab-TedTalks_v1_mono.ko.gz 
    - data/ko/opus/OPUS-wikimedia_v20230407_mono.ko.gz 
    - data/ko/opus/OPUS-KDE4_v2_mono.ko.gz 
    - data/ko/opus/OPUS-Mozilla-I10n_v1_mono.ko.gz 
    - data/ko/opus/OPUS-bible-uedin_v1_mono.ko.gz 
    - data/ko/opus/OPUS-GlobalVoices_v2018q4_mono.ko.gz 
    - data/ko/opus/OPUS-Tatoeba_v2023-04-12_mono.ko.gz 
    - data/ko/opus/OPUS-Tanzil_v1_mono.ko.gz 
    - data/ko/opus/OPUS-ELRC-3070-wikipedia_health_v1_mono.ko.gz 
    - data/ko/opus/OPUS-ELRC_2922_v1_mono.ko.gz 
    - data/ko/opus/OPUS-ELRC-wikipedia_health_v1_mono.ko.gz 
    - data/ko/opus/OPUS-Ubuntu_v14.10_mono.ko.gz 
    - data/ko/opus/OPUS-GNOME_v1_mono.ko.gz
    - data/ko/wmt/news.2018.ko.shuffled.deduped.gz 
    - data/ko/wmt/news.2019.ko.shuffled.deduped.gz 
    - data/ko/wmt/news.2020.ko.shuffled.deduped.gz 
    - data/ko/wmt/news.2021.ko.shuffled.deduped.gz
    - data/ko/wmt/news.2022.ko.shuffled.deduped.gz
    - data/ko/tatoeba_20230818.ko.gz 

  train_labels_file:
    - data/enko/opus/CCMatrix.en-ko.en.gz
    - data/enko/opus/CCAligned.en-ko.en.gz
    - data/enko/opus/LinguaTools-WikiTitles.en-ko.en.gz
    - data/enko/opus/ParaCrawl.en-ko.en.gz
    - data/enko/opus/XLEnt.en-ko.en.gz
    - data/enko/opus/OpenSubtitles.en-ko.en.gz
    - data/enko/opus/QED.en-ko.en.gz
    - data/enko/opus/TED2020.en-ko.en.gz
    - data/enko/opus/WikiMatrix.en-ko.en.gz
    - data/enko/opus/NeuLab-TedTalks.en-ko.en.gz
    - data/enko/opus/wikimedia.en-ko.en.gz
    - data/enko/opus/Tanzil.en-ko.en.gz
    - data/enko/opus/KDE4.en-ko.en.gz
    - data/enko/opus/bible-uedin.en-ko.en.gz
    - data/enko/opus/PHP.en-ko.en.gz
    - data/enko/opus/GlobalVoices.en-ko.en.gz
    - data/enko/opus/Tatoeba.en-ko.en.gz
    - data/enko/opus/ELRC-3070-wikipedia_health.en-ko.en.gz
    - data/enko/opus/ELRC-wikipedia_health.en-ko.en.gz
    - data/enko/opus/ELRC_2922.en-ko.en.gz
    - data/enko/opus/Ubuntu.en-ko.en.gz
    - data/enko/opus/GNOME.en-ko.en.gz
    - data/enko/mttt/mttt_train_en-ko.raw.en.gz
    - data/enko/opus/CCMatrix.en-ko.ko.gz
    - data/enko/opus/CCAligned.en-ko.ko.gz
    - data/enko/opus/LinguaTools-WikiTitles.en-ko.ko.gz
    - data/enko/opus/ParaCrawl.en-ko.ko.gz
    - data/enko/opus/XLEnt.en-ko.ko.gz
    - data/enko/opus/OpenSubtitles.en-ko.ko.gz
    - data/enko/opus/QED.en-ko.ko.gz
    - data/enko/opus/TED2020.en-ko.ko.gz
    - data/enko/opus/WikiMatrix.en-ko.ko.gz
    - data/enko/opus/NeuLab-TedTalks.en-ko.ko.gz
    - data/enko/opus/wikimedia.en-ko.ko.gz
    - data/enko/opus/Tanzil.en-ko.ko.gz
    - data/enko/opus/KDE4.en-ko.ko.gz
    - data/enko/opus/bible-uedin.en-ko.ko.gz
    - data/enko/opus/PHP.en-ko.ko.gz
    - data/enko/opus/GlobalVoices.en-ko.ko.gz
    - data/enko/opus/Tatoeba.en-ko.ko.gz
    - data/enko/opus/ELRC-3070-wikipedia_health.en-ko.ko.gz
    - data/enko/opus/ELRC-wikipedia_health.en-ko.ko.gz
    - data/enko/opus/ELRC_2922.en-ko.ko.gz
    - data/enko/opus/Ubuntu.en-ko.ko.gz
    - data/enko/opus/GNOME.en-ko.ko.gz
    - data/enko/mttt/mttt_train_en-ko.raw.ko.gz
    - 
    -  
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
    - 
