from multitasknmt.generateSpanCorruption import generateSpanCorruption
from multitasknmt.generateTranslationSpanCorruption import generateTranslationSpanCorruption
from multitasknmt.generateTranslationPairSpanCorruption import generateTranslationPairSpanCorruption
from multitasknmt.generateMTPrompt import generateMTPrompt

from multitasknmt.spanCorruption_inputter import SpanCorruptionInputter
from multitasknmt.translationSpanCorruption_inputter import TranslationSpanCorruptionInputter
from multitasknmt.translationPairSpanCorruption_inputter import TranslationPairSpanCorruptionInputter
from multitasknmt.examplesMTPrompt_inputter import ExamplesMTPromptInputter
from multitasknmt.sc_tpsc_tsc_mt_inputter import ScTpscTscMtInputter